version: "3.9"
services:
  server:
    image: webserver
    build:
      context: .
      dockerfile: ${DOCKERFILE}
    command:
      - "-addr"
      - "0.0.0.0:8000"
      - "-delay"
      - "200"
      - "-dprob"
      - "100"
      - "-cancel"
      - "-cprob"
      - "0"
    ports:
      - "8000:8000"
      - "10000:10000"
    networks:
      - testnet
  traffgen:
    image: williamyeh/hey:latest
    command:
      - "-n"
      - "76000"
      - "-c"
      - "2000"
      - "-m"
      - "GET"
      - "http://server:8000/echo"
    depends_on:
      - server
    networks:
      - testnet

networks:
  testnet: {}
