FROM python:3.10.4-alpine3.15

RUN mkdir -p /app/src
WORKDIR /app

RUN apk add --no-cache --virtual .build-deps g++ python3-dev libffi-dev openssl-dev && \
    apk add --no-cache --update python3 && \
    pip3 install --upgrade pip setuptools

COPY fastapi/requirements.txt .
RUN pip install -r requirements.txt

COPY fastapi/src/ /app/src
WORKDIR /app/src
ENTRYPOINT ["python3", "server.py"]
