FROM python:3.10.4-alpine3.15

RUN mkdir -p /app/src
WORKDIR /app
COPY flask/requirements.txt .
RUN pip install -r requirements.txt

COPY flask/src/ /app/src
WORKDIR /app/src
ENTRYPOINT ["python3", "server.py"]
