FROM python:3.7.12-alpine

RUN mkdir -p /app/src
WORKDIR /app
COPY flask/requirements.txt .
RUN pip install -r requirements.txt

COPY flask/src/ /app/src
WORKDIR /app/src
ENTRYPOINT ["python3", "server.py"]
